# Generated by Django 4.1.13 on 2024-03-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('student_id', models.CharField(default=None, max_length=9, null=True)),
                ('student_name', models.CharField(default=None, max_length=20, null=True)),
                ('phone_num', models.CharField(default=None, max_length=13, null=True)),
                ('rental_date', models.DateTimeField(default=None, null=True)),
                ('deadline_date', models.DateTimeField(default=None, null=True)),
                ('state', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('no', 'name'), name='물품별 고유 번호 부여'),
        ),
    ]
