# Generated by Django 4.1.13 on 2024-03-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='count',
        ),
        migrations.AddField(
            model_name='item',
            name='deadline_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='rental_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='student_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='student_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
