# Generated by Django 4.1.13 on 2024-03-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_item_no_item_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rental_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='student_id',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='student_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
