# Generated by Django 4.1.13 on 2024-03-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_item_rental_date_alter_item_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
