# Generated by Django 4.1.13 on 2024-03-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_item_물품별 고유 번호 부여'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='phone_num',
            field=models.CharField(default='010-1111-1111', max_length=13),
            preserve_default=False,
        ),
    ]
